---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
rules:
  - apiGroups:
      - ""
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: user-workload-dashboard
