apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/user-workload-rbac
namespace: ns1
patches:
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: grafana
      subjects:
        - kind: ServiceAccount
          name: grafana
          namespace: app-monitoring
